{
 "title": "pubsub",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "stackdriver" },
   {
    "name": "projectId",
    "query": {}
   },
   {
    "name": "budget",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Ack message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oldest retained acked message age",
   "type": "gauge",
   "description": "Age (in seconds) of the oldest acknowledged message retained in a subscription.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/oldest_retained_acked_message_age",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/oldest_retained_acked_message_age",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Retained acked messages",
   "type": "gauge",
   "description": "Number of acknowledged messages retained in a subscription.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_retained_acked_messages",
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_retained_acked_messages",
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Retained acked messages",
   "type": "timeseries",
   "description": "Number of acknowledged messages retained in a subscription.",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_retained_acked_messages",
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_retained_acked_messages",
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Retained acked bytes",
   "type": "gauge",
   "description": "Total byte size of the acknowledged messages retained in a subscription.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/retained_acked_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/retained_acked_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Ack Latency",
   "type": "timeseries",
   "description": "Distribution of ack latencies in milliseconds. The ack latency is the time between when Cloud Pub/Sub sends a message to a subscriber client and when Cloud Pub/Sub receives an Acknowledge request for that message.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Distribution of ack latencies in seconds",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/subscription/ack_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Ack message count",
   "type": "timeseries",
   "description": "Cumulative count of messages acknowledged by Acknowledge requests, grouped by delivery type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Cumulative count of messages acknowledged",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/subscription/ack_message_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pull requests & Pull operations",
   "type": "timeseries",
   "description": "Cumulative count of pull requests, grouped by result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Pull Requests",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/subscription/pull_request_count",
      "perSeriesAligner": "ALIGN_MIN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Pull operations",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/subscription/pull_message_operation_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Publish requests & Publish message operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Publish Requests",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.topic_id",
       "=",
       "$budget"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/topic/send_request_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Publish message operations",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.topic_id",
       "=",
       "$budget"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "pubsub.googleapis.com/topic/send_message_operation_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "Unack message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Unacked messages",
   "type": "graph",
   "description": "Number of unacknowledged messages (a.k.a. backlog messages) in a subscription.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "msg" } },
   "yaxes": [
    { "format": "msg" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Unacknowledged Messages on Form Topic",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Unacknowledged Messages on Dead Letter Sub",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Unacked messages",
   "type": "gauge",
   "description": "Number of unacknowledged messages (a.k.a. backlog messages) in a subscription.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "msg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Oldest Unacked message age",
   "type": "gauge",
   "description": "Age (in seconds) of the oldest unacknowledged message (a.k.a. backlog message) in a subscription.",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/oldest_unacked_message_age",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/oldest_unacked_message_age",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backlog Bytes",
   "type": "gauge",
   "description": "Total byte size of the unacknowledged messages (a.k.a. backlog messages) in a subscription.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/backlog_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/backlog_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backlog Size",
   "type": "state-timeline",
   "description": "Total byte size of the unacknowledged messages (a.k.a. backlog messages) in a subscription.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Form Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${subscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/backlog_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Dead Letter Subscription",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "${deadLetterSubscriptionId}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/backlog_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}